version: '3.8'

networks:
  sif-network:
    driver: bridge

volumes:
  backend_data:
  backend_models:
  backend_backups:

services:
  backend:
    container_name: sif-backend
    image: sif-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - backend_data:/app/backend/data/processed
      - backend_data:/app/backend/data/uploads
      - backend_models:/app/backend/data/models
      - backend_backups:/app/backend/data/backups
      - ./backend/app.log:/app/backend/app.log
      - ./backend/jwt_secret.key:/app/backend/jwt_secret.key
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - sif-network

  frontend:
    container_name: sif-frontend
    image: sif-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend
    networks:
      - sif-network